apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlepedido-database-pod
spec:
  selector:
    matchLabels:
      app: controlepedido-database-pod
  template:
    metadata:
      labels:
        app: controlepedido-database-pod
    spec:
      containers:
        - name: controlepedido-database-pod
          image: postgres:12
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: controle-pedido-database-configmap
                  key: DbName
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim: 
            claimName: controlepedido-database-pvc
