# templates/deployment1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.deployment.name }}
spec:
  replicas: {{ .Values.api.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.api.deployment.name }}
        image: {{ .Values.api.deployment.image.repository }}:{{ .Values.api.deployment.image.tag }}
        ports:
          - containerPort: 443  # Porta HTTPS dentro do contêiner
          - containerPort: 80   # Porta HTTP dentro do contêiner
        env:
          - name: {{.Values.api.configmap.key}}   # Nome da variável de ambiente para a conexão com o banco de dados
            valueFrom:
              configMapKeyRef:
                name: {{.Values.api.configmap.name}}  # Nome do ConfigMap que contém a configuração
                key: {{.Values.api.configmap.key}}  # Chave dentro do ConfigMap que contém a string de conexão
        resources:
            requests:
              cpu: "256m"
              memory: "512Mi"
            limits:
              cpu: "512m"
              memory: "1024Mi"
