apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.api.hpa.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment  # Tipo de recurso que está sendo escalado
    name: {{.Values.api.deployment.name}}  # Nome do deployment que você deseja escalar
  minReplicas: {{.Values.api.hpa.minReplicas}}  # Número mínimo de réplicas
  maxReplicas: {{.Values.api.hpa.maxReplicas}}  # Número máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.api.hpa.cpuAverageUtilization}}  # Alvo de utilização de CPU (60%)
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{.Values.api.hpa.memoryAverageUtilization}}  # Alvo de utilização de memória (60%)
